package cz.kamosh.hhh5645.entity;
// Generated Apr 9, 2014 6:49:28 PM by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * TableC generated by hbm2java
 */
public class TableC implements java.io.Serializable {

    private long tableCId;
    private TableB tableB;
    private String tableCChar;
    private Date tableCDate;
    private Boolean tableCBoolean;
    private Integer tableCInteger;

    public TableC() {
    }

    public TableC(long tableCId) {
        this.tableCId = tableCId;
    }

    public TableC(long tableCId, TableB tableB, String tableCChar, Date tableCDate, Boolean tableCBoolean, Integer tableCInteger) {
        this.tableCId = tableCId;
        this.tableB = tableB;
        this.tableCChar = tableCChar;
        this.tableCDate = tableCDate;
        this.tableCBoolean = tableCBoolean;
        this.tableCInteger = tableCInteger;
    }

    public long getTableCId() {
        return this.tableCId;
    }

    public void setTableCId(long tableCId) {
        this.tableCId = tableCId;
    }

    public TableB getTableB() {
        return this.tableB;
    }

    public void setTableB(TableB tableB) {
        this.tableB = tableB;
    }

    public String getTableCChar() {
        return this.tableCChar;
    }

    public void setTableCChar(String tableCChar) {
        this.tableCChar = tableCChar;
    }

    public Date getTableCDate() {
        return this.tableCDate;
    }

    public void setTableCDate(Date tableCDate) {
        this.tableCDate = tableCDate;
    }

    public Boolean getTableCBoolean() {
        return this.tableCBoolean;
    }

    public void setTableCBoolean(Boolean tableCBoolean) {
        this.tableCBoolean = tableCBoolean;
    }

    public Integer getTableCInteger() {
        return this.tableCInteger;
    }

    public void setTableCInteger(Integer tableCInteger) {
        this.tableCInteger = tableCInteger;
    }

}
